export const GENRES = [
  "FICTION", "NON_FICTION", "MYSTERY", "THRILLER", "FANTASY", "SCIENCE_FICTION", "ROMANCE",
  "HISTORICAL", "HORROR", "BIOGRAPHY", "SELF_HELP", "POETRY", "DRAMA", "ADVENTURE", "CRIME",
  "YOUNG_ADULT", "CHILDREN", "CLASSICS",
];

export const COPY_STATUSES = ["AVAILABLE", "LOANED", "DAMAGED", "LOST"];

